### ISSUE TITLE
As a user, I can pause and start recording at will.

### ISSUE THREAD

**Issue by rfbonett** [rfbonett/CSCi435-ODBR#5]

**Comment by bwotten** [comment]
67580c763e4a118d4ed3fdbf17479da81d5f5e76

**Comment by bwotten** [comment]
aa9048a858ef9cf741943ee0f47d251db8875d48

**Comment by rfbonett** [comment]
77b1f7082d8977e042ef4691ec3f6da663eb1e81

**Comment by rfbonett** [comment]
29132c842a2257bd7233c085f21f95db7214cc9e
